### PR TITLE
Added recent articles; revised some stuff

### PR DESCRIPTION
**Pull request by lingeringcode**
Hi Tim,

Happy Thanksgiving Eve. :-)

I saw your project, and I thought I'd pitch in. LMK what you think.

Here's a short summary of what I added / changed:

1. Added dynamic xml/rdf reader of some major rhet, writing, and tc journals, which renders dynamically on the new articles.htm page. 
2. The other major new files also include the js/writer.js and the js/parser.js. I wrote the former to parse provided rdf feed data from some available journals. The parser.js file is a code lib, which the writer.js uses a bit.
3. I made some small revisions to the HTML/CSS: indentation, spacing, some HTML structuring to the pages. Specifically, I altered the navigation a bit, so it's a bit more semantic. Yet, I left the original, so feel free to consider things.

### CODE REVIEW

**Comment by lingeringcode** [comment]
Tim, I forgot about the CORS req issue, since I originally wrote this for a Node app, prior to rewriting it for your site. Plus, I used a Chrome extension to test my use of the parser.js lib, so I got a little overzealous making this PR. lol :-)

I'll need to research the solution a bit more, since the issue has become more hairy over the past few years.

**Comment by lingeringcode** [comment]
Well, it's looking pretty bleak. I wish I could have contributed a new part to your site, but there's currently no way to make this request in a [client-side js file](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest#Cross-site_XMLHttpRequest). 

To make it work, I would need to write the files to "our" server first before parsing the info, which is what my node app was doing. Buggard. :-(

**Comment by timlockridge** [comment]
Thanks, Chris. This is a great idea!

I stayed away from journals with this project partially because of the complexity. Only a few offer any kind of feed, and there are *so many* journals & journal articles. There are comparatively few books & I can manually curate a json file without too much of a time commitment. Compiling all the journal articles in a year would be a larger task (and I think the difficulty of that task speaks to the uneven archives of Comppile and the Eserver Tech Comm library) and a larger time sink. It also, perhaps, introduces some messy questions about what journals are included and what aren't and how that possibly constructs the discipline. So I opted to go with monographs & a Google Form for the inclusion of things that I would miss or that I wouldn't see as part of the field (but that others helpfully might).

I think the journal project should probably be a separate website; I don't know that it can achieve the comprehensiveness that I would like to get with monographs (although that kind of comprehensiveness at the journal level would be an awesome goal!). However, I would encourage you to consider pursuing this as a standalone thing. It could be a truly helpful website, and the field would benefit from your programming knowledge! I also think there could also be a great outreach project there—helping small journals learn how to syndicate their content with RSS or json feed. That alone would be a wonderful gift to the discipline.

**Comment by lingeringcode** [comment]
You raise some really good points about comprehensiveness. I was surprised, (but not so much), how journals outside of the pub industry lacked feeds. I would've thought that the CMSes that OA journals use these days have such features by now. Yet, I've noticed that some of the newest journals in R/C still opt to use systems like Wordpress unfortunately. LiCS created a rudimentary RSS feed with a RDF output, so that's a good start! I didn't include it in this proto, because their feed does not follow the industry standards, so it would have meant more coding for this little experiment. :-)

If you plan to keep using Google Forms, would you be interested in using Google's Sheets API as a means to render the books? I do something like this already with Ridolfo's market comparison data. Instead of manually inputting, outputting, and uploading the data, you would could output the approved Form submission to a yearly sheet within a main Sheets spreadsheet. From there, I could create a script that outputs the appropriate sheet as a JSON object to use in the `table.setData()`. LMK if you'd like to try it out.

**Comment by timlockridge** [comment]
Fantastic! I don't think I'm ready for that in the near term, but I will follow up with you in the Spring. Some parts of the site are kinda sloppy at the moment (I wanted to launch the thing first and then iterate), and some are waiting on javascript features I need to add. I'm going to use those future features as a way to learn a few new things, so let me follow up with you once I've built on the site a bit. The Google Sheets API addition sounds really handy, but I want to make sure it fits into my workflow for dealing with publisher-submitted books and for my approach to archiving the data—as well as my personal pedagogical practice of learning new some stuff :) So in short, let me figure out my approach & process & I'll follow up!

**Pull request closed without merging**
